### ISSUE TITLE
应用强杀后，报错停止运行

### ISSUE THREAD

**Issue by Tlaurus** [Doublemine/AutoUpdate#2]
```java
   Process: tech.honc.apps.android.djplatform, PID: 21496
                                                                                   java.lang.RuntimeException: Unable to start service work.wanghao.autoupdate.service.DefaultDownloadService@41ef6d10 with null: java.lang.NullPointerException
                                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2863)
                                                                                       at android.app.ActivityThread.access$2100(ActivityThread.java:155)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5426)
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                                    Caused by: java.lang.NullPointerException
                                                                                       at work.wanghao.autoupdate.service.BaseUpdateService.setupFirTask(BaseUpdateService.java:236)
                                                                                       at work.wanghao.autoupdate.service.BaseUpdateService.onStartCommand(BaseUpdateService.java:69)
                                                                                       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2846)
                                                                                       at android.app.ActivityThread.access$2100(ActivityThread.java:155) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5426) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                                       at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Doublemine** [comment]
感谢反馈，已修复
